name = "cloudclipboard-pages"
compatibility_date = "2024-01-01"

# D1 数据库绑定在 Cloudflare Pages 仪表盘中手动配置

# 环境变量
[vars]
TABLE_NAME = "cloudclipboard"
# ACCESS_PASSWORD = "your-password-here"  # 在Cloudflare Pages设置中配置