name = "cloudclipboard-pages"
compatibility_date = "2024-01-01"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "cloudclipboard"
database_id = "your-database-id-here"

# 环境变量
[vars]
TABLE_NAME = "799e56cb-fb70-49a5-a4a1-84747d0ac01d"