name = "cloudclipboard-pages"
compatibility_date = "2024-01-01"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "cloudclipboard"
database_id = "your-database-id-here"

# 环境变量
[vars]
TABLE_NAME = "cloudclipboard"
# ACCESS_PASSWORD = "your-password-here"  # 在Cloudflare Pages设置中配置